name: Despliegue de Arquitectura Completa a AWS ECS

on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: Cluster-Innovatech-Prod
  ECR_FRONT: innovatech-frontend
  ECR_VENTAS: innovatech-back-ventas
  ECR_DESPACHOS: innovatech-back-despachos

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS Academy
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Iniciar sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir y Subir FRONTEND a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/${{ env.ECR_FRONT }}:latest ./front_despacho
        docker push $ECR_REGISTRY/${{ env.ECR_FRONT }}:latest

    - name: Construir y Subir BACKEND VENTAS a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/${{ env.ECR_VENTAS }}:latest ./back-Ventas_SpringBoot
        docker push $ECR_REGISTRY/${{ env.ECR_VENTAS }}:latest

    - name: Construir y Subir BACKEND DESPACHOS a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/${{ env.ECR_DESPACHOS }}:latest ./back-Despachos_SpringBoot
        docker push $ECR_REGISTRY/${{ env.ECR_DESPACHOS }}:latest